name: Sunflower Flutter CI/CD

on:
  push:
    branches:
      - "**" #trigger on all branches

  workflow_dispatch:  # Allows manually triggering the workflow with inputs
    inputs:
      build_type:
        description: 'Choose build type (apk or appbundle)'
        required: true
        default: 'apk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK or App Bundle
        run: |
          if [ "${{ inputs.build_type }}" == "apk" ]; then
            flutter build apk --release --split-per-abi
          elif [ "${{ inputs.build_type }}" == "appbundle" ]; then
            flutter build appbundle --release
          fi

      - name: Upload APKs (if APK was built)
        if: ${{ inputs.build_type == 'apk' }}
        uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk

      - name: Upload App Bundle (if App Bundle was built)
        if: ${{ inputs.build_type == 'appbundle' }}
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
